### ISSUE TITLE
Page - Bundle Structure

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#10]
The Bundle Structure page (https://developer.nhs.uk/apis/ems-beta/explore_bundle_structure.html) could benefit from the following changes:

1. There is a word  reapeat "contain contain" one needs removing.

2. This page is a good one but It might be good to consider if there is a way of showing the links between the resource within the diagrams. It just feels like this is not made clear at the moment within the spec.

3. The header and data sections could probably be merged into one diagram, it feels like the example in the data section has too much information but not correct details to be useful.

**Comment by bushra** [comment]
1. This has been corrected.
2. A example resource model will be added (this apply to the Failsafe and Demographic Updates specifications also)
3. I think the header and data sections require differentiation, because it gives a view of the mandatory header information for all event messages received/published by EMS.
