### ISSUE TITLE
Page - Error Handling

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#12]
The Error Handling (https://developer.nhs.uk/apis/ems-beta/explore_errors.html) page would benefit from the following changes to the specification:

1. The url for the page might be better being "error_handling" rather than "explore_errors".

2.  There is a link to the spine core spec, but the link is to a non static version of the spine core specification. We should reference a static version of the specification so that when someone looks at this version of the NEMS spec they always see the spine core spec which was correct at the point where the specification was release. If we link to the current (latest) version of the spine core spec they could introduce a breaking change or additional changes we have not taken into consideration for the NEMS spec, which could cause problems for suppliers who build against that later core spec when they interact with the NEMS apis.

3. The "Event Message Response" link does not work and leads to a 404.

**Comment by bushra** [comment]
1. The url for the page might be better being "error_handling" rather than "explore_errors". - This change has been applied.
3. The "Event Message Response" link does not work and leads to a 404. - This reference has been removed as the Event Message Response has been replaced by the guidance in the Error Handling section.
Point 2 will require comment from @ahatherly or @fletch1975

**Comment by james-answer** [comment]
Links to static version of spine core and other external specs will be raised as a seperate github issue. All other points on this issue have been fixed so I am closing as the changes are in gh-pages.
