### ISSUE TITLE
Need to put guidance within the spec around LEMS

### ISSUE THREAD

**Issue by james-answer** [nhsconnect/Events-Management#21]
During a meeting the requirements around LEMS use of the NEMS was discussed. These requirements and assumptions should be included in the specification. Currently the following is being considered but needs to be descussed further and included in the specificaiton:

- it was genreally agreed that aggregators such as LEMS may subscribe to events but may not publish events as the provenance of the sending system can not be assured. If publishing by LEMS is required it can be considered and specified in a later version of the specification.
- guidance should be added to the specification that rather than propagating the data down to other systems those downstream systems should be encouraged to connect to NEMS directly.

**Comment by fletch1975** [comment]
Issue 1 - Not to be included in the specification. 
- A publisher (supplier) will be given direction on whether they should be publishing events to the NEMS, a LEMS or both. If they need to publish to the NEMS they will use our specification. 
- A subscriber (supplier) will be given direction on whether they should be subscribing to events from the NEMS or a LEMS. If they need to subscribe to the NEMS they will use our specification.

When clear guidance is available the specifications can link out to it but this is not required at the current time.

Issue 2 - part of TOM rather than the specification.

**Comment by james-answer** [comment]
Agree, as there is nothing to change within the specification I will close this github issue.
